on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    

jobs:
  trigger-test:
    runs-on: ubuntu-latest

    steps:
    - name: trigger automated tests in another repo
      uses: peter-evans/repository_dispatch@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: pbetala/tests-temp
        event-type: my-event
        client-payload: '{"github": ${{ toJson(github) }}}'
